MvcNetCoreZapatillas/Models/ErrorViewModel.cs
namespace MvcNetCoreZapatillas.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcNetCoreZapatillas/Models/ImagenZapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCoreZapatillas.Models
{
    [Table("IMAGENESZAPASPRACTICA")]
    public class ImagenZapatilla
    {
        [Key]
        [Column("IDIMAGEN")]
        public int IdImagen { get; set; }
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("IMAGEN")]
        public string Imagen { get; set; }
    }
}

MvcNetCoreZapatillas/Models/ModelPaginarZapatilla.cs
namespace MvcNetCoreZapatillas.Models
{
    public class ModelPaginarZapatilla
    {
        public ImagenZapatilla ImagenZapatilla { get; set; }
        public int NumeroRegistros { get; set; }
    }
}

MvcNetCoreZapatillas/Models/Zapatilla.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcNetCoreZapatillas.Models
{
    [Table("ZAPASPRACTICA")]
    public class Zapatilla
    {
        [Key]
        [Column("IDPRODUCTO")]
        public int IdProducto { get; set; }
        [Column("NOMBRE")]
        public string Nombre { get; set; }
        [Column("DESCRIPCION")]
        public string Descripcion { get; set; }
        [Column("PRECIO")]
        public int Precio { get; set; }
    }
}

MvcNetCoreZapatillas/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreZapatillas.Models;
using System.Diagnostics;

namespace MvcNetCoreZapatillas.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcNetCoreZapatillas/Controllers/ZapatillasController.cs
using Microsoft.AspNetCore.Mvc;
using MvcNetCoreZapatillas.Models;
using MvcNetCoreZapatillas.Repositories;

namespace MvcNetCoreZapatillas.Controllers
{
    public class ZapatillasController : Controller
    {
        RepositoryZapatillas repo;
        public ZapatillasController(RepositoryZapatillas repo)
        {
            this.repo = repo;
        }

        public async Task<IActionResult> Zapatillas()
        {
            List<Zapatilla> zapatillas = await this.repo.GetZapatillas();
            return View(zapatillas);
        }

        public async Task<IActionResult> DetallesZapatilla(int? idposicion, int idproducto)
        {
            if(idposicion == null)
            {
                idposicion = 1;
            }
            ViewData["POSICION"] = idposicion;
            Zapatilla zapatilla = await this.repo.GetZapatilla(idproducto);
            return View(zapatilla);
        }

        public async Task<IActionResult> _ImagenesZapatilla(int idposicion, int idproducto)
        {
            ModelPaginarZapatilla modelZapatilla = await this.repo.GetImagenZapatilla(idposicion, idproducto); 
            return PartialView("_ImagenesZapatilla", modelZapatilla);
        }

        //public async Task<IActionResult> Imagenes(int idposicion, int idproducto)
        //{
        //    ModelPaginarZapatilla modelZapatilla = await this.repo.GetImagenZapatilla(idposicion, idproducto);
        //    return View(modelZapatilla);
        //}
    }
}

MvcNetCoreZapatillas/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">ZAPATILLAS</h1>
    <a asp-controller="Zapatillas" asp-action="Zapatillas" class="btn btn-info">INICIO</a>
</div>

MvcNetCoreZapatillas/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcNetCoreZapatillas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcNetCoreZapatillas.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="https://static.vecteezy.com/system/resources/thumbnails/010/994/412/small/nike-logo-black-with-name-clothes-design-icon-abstract-football-illustration-with-white-background-free-vector.jpg"
                         style="width: 60px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zapatillas" asp-action="Zapatillas">Zapatillas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MvcNetCoreZapatillas - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MvcNetCoreZapatillas/Views/Zapatillas/DetallesZapatilla.cshtml
@model MvcNetCoreZapatillas.Models.Zapatilla

@{
    ViewData["Title"] = "DetallesZapatilla";
}

@{
    int posicion = (int)ViewData["POSICION"];
}

@section Scripts{
    <script>
        $(document).ready(function() {
            $("#imagenes").load("/Zapatillas/_ImagenesZapatilla?idposicion=@posicion&idproducto=@Model.IdProducto")
        })

        function hola(posicion, producto) {
            $("#imagenes").load("/Zapatillas/_ImagenesZapatilla?idposicion=" +posicion+ "&idproducto="+producto)
        }
    </script>
}

    <h1>DetallesZapatilla</h1>

    <div>
        <h4>Zapatilla</h4>
        <hr />
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IdProducto)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IdProducto)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Nombre)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Nombre)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Descripcion)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Descripcion)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Precio)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Precio)
            </dd>
        </dl>
    </div>
    <div id="imagenes"></div>
    <div>
        <a asp-action="Zapatillas">Back to List</a>
    </div>
@*    <div>
        <a asp-action="Imagenes" asp-route-idposicion="1" asp-route-idproducto="@Model.IdProducto">Imagenes</a>
    </div>*@

MvcNetCoreZapatillas/Views/Zapatillas/Imagenes.cshtml
@model ModelPaginarZapatilla

<div class="card" style="width: 18rem;">
    <div class="card-body">
        <ul class="list-group list-group-horizontal">
            @for (int i = 1; i <= Model.NumeroRegistros; i++)
            {
                <li class="list-group-item list-group-item-success">
                    <a href="/Zapatillas/_ImagenesZapatilla?idposicion=@i&idproducto=@Model.ImagenZapatilla.IdProducto">
                        Página @i
                    </a>
                </li>
            }
        </ul>
        <img src="@Model.ImagenZapatilla.Imagen" width="150" height="150"/>
    </div>
</div>

MvcNetCoreZapatillas/Views/Zapatillas/Zapatillas.cshtml
@model IEnumerable<MvcNetCoreZapatillas.Models.Zapatilla>

@{
    ViewData["Title"] = "Zapatillas";
}

<h1>Zapatillas</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdProducto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descripcion)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Precio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.IdProducto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descripcion)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Precio)
                </td>
                <td>
                    @Html.ActionLink("Detalles", "DetallesZapatilla", new { idproducto = @item.IdProducto })
                </td>
            </tr>
        }
    </tbody>
</table>

MvcNetCoreZapatillas/Views/Zapatillas/_ImagenesZapatilla.cshtml
@model ModelPaginarZapatilla

@*@section Scripts{
    <script>
        $(document).ready(function() {
            $("button").click(function() {
                var idposicion = $(this).data("idposicion");
                var idproducto = $(this).data("idproducto");

                $("#card").load("/Zapatillas/_DetallesZapatilla?idposicion="+idposicion+"&idproducto="+idproducto)
            })
        })
    </script>
}*@

<div class="card" style="width: 18rem;" id="card">
    <div class="card-body">
        <ul class="list-group list-group-horizontal">
            @for (int i = 1; i <= Model.NumeroRegistros; i++)
            {
                <li class="list-group-item list-group-item-success">
                @*<a href="/Zapatillas/_ImagenesZapatilla?idposicion=@i&idproducto=@Model.ImagenZapatilla.IdProducto">
                        @i
                    </a>*@
                    <button data-idposicion="@i" data-idproducto="@Model.ImagenZapatilla.IdProducto" onclick="hola(@i, @Model.ImagenZapatilla.IdProducto)" class="btn btn-success">@i</button>
                </li>
            }
        </ul>
        <img src="@Model.ImagenZapatilla.Imagen" width="150" height="150"/>
    </div>
</div>